service: typescritpt-esbuild
frameworkVersion: '>=3.30.0 <4.0.0'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  memorySize: 128
  timeout: 5 # seconds
  versionFunctions: false
  logRetentionInDays: 30
  stage: ${opt:stage, 'dev'}
  environment:
    TZ: Asia/Tokyo
    NODE_OPTIONS: '--enable-source-maps'

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
    watch:
      pattern: ['src/**/*.ts'] # match only typescript files in src directory

package:
  individually: true

functions:
  lambda:
    handler: src/handler.handler
    name: ${self:service}
